### ISSUE TITLE
possible race condition on cell.subscribers

### ISSUE THREAD

**Issue by kung-foo** [tideland/golib#3]
Using `go build -race` I noticed a race condition when using `cell.SubscribersDo()`.

In `cell.backendLoop()` there is a write to `c.subscribers` after reading from the `subscriberc` channel. The `SubscribersDo` should probably go through a ReadLock?

**Comment by TheMue** [comment]
Will check and fix it, thanks. I appreciate your feedback.

**Comment by TheMue** [comment]
Fixed subscribers handling.
