### ISSUE TITLE
Basic usage information for getting started with logger

### ISSUE THREAD

**Issue by vondeetzen** [tideland/golib#36]
Today I got a little stuck when starting to use logger. I had to scan reference documentation to figure it out. A little getting started or basic usage guide would had helped me to save some time and get the concept of e.g. different loggers (like Gologger, StandardLogger, etc.).

I've created very basic usage information for logger and pushed it to https://github.com/vondeetzen/golib in order to get some feedback. Thanks in advance.

**Comment by themue** [comment]
Hi André, thx for the docs. Normally usage information are more in the package documentation, so it can be browsed in https://godoc.org/. I'll add you information (and more) to the package documentation but will also extend the *advertising paragraph* of the README.
