### ISSUE TITLE
cell.ProcessEvent

### ISSUE THREAD

**Issue by kung-foo** [tideland/golib#4]
https://github.com/tideland/golib/blob/master/cells/cell.go#L137

This should probably use `<-time.After(time.Second)` rather than a straight `time.Sleep()`. I don't have a test case for it yet, but I did see in some of my code where if `eventc` got backed up a little then the `ProcessEvent` loop would pause for one second, even though it was able to continue processing after only a few milliseconds.

```go
func (c *cell) ProcessEvent(event Event) error {
	start := time.Now()
	for {
		select {
		case c.eventc <- event:
			return nil
		case <-c.loop.IsStopping():
			return errors.New(ErrInactive, errorMessages, c.id)
		case <-time.After(time.Second):
			now := time.Now()
			if now.Sub(start) > c.emitTimeout {
				op := fmt.Sprintf("emitting %q to %q", event.Topic(), c.id)
				return errors.New(ErrTimeout, errorMessages, op)
			}
		}
	}
}
```

**Comment by TheMue** [comment]
Looks better, indeed. Maybe it even makes sense to make this time configurable. Will think about. Thanks for your great input.

**Comment by kung-foo** [comment]
You could also probably make it:

```go
case <-time.After(c.emitTimeout):
```

right?

**Comment by TheMue** [comment]
Yeah, great, and simplifies the code more.

**Comment by kung-foo** [comment]
of course, we can go further:

```go
func (c *cell) ProcessEvent(event Event) error {
	c.emitTimer.Reset(c.emitTimeout)
	select {
	case c.eventc <- event:
		return nil
	case <-c.loop.IsStopping():
		return errors.New(ErrInactive, errorMessages, c.id)
	case <-c.emitTimer.C:
		op := fmt.Sprintf("emitting %q to %q", event.Topic(), c.id)
		return errors.New(ErrTimeout, errorMessages, op)
	}
}
```

This saves an allocation of a new timer on each `ProcessEvent`

**Comment by TheMue** [comment]
Get's even better, yes. Should think about hiring you. Sadly I'm only private. ;)

**Comment by kung-foo** [comment]
Though there might be something wrong with reusing a timer like that. Not sure what happens it writes to the channel (`C`) but no one reads from it. Maybe a `defer c.emitTimer.Stop()`...

Hard for me to track this one down because in my case, I am processing about 1M events per second across 1000 cells. :)

We are also hiring, but you'd have to want to move to Norway.

**Comment by TheMue** [comment]
Wow, what an impressive value. My own tests never created such a huge environment. Would like to know more about your use case for cells. If it's no secret let me know at mue(at)tideland.biz.

Regarding the time I'll do some research.

**Comment by kung-foo** [comment]
Seems to be a bit more complicated than I first thought:
https://github.com/golang/go/issues/4412
https://github.com/golang/go/issues/11662

Even with the first pass of `<-time.After(...)` results in this huge leak for me:

```
(pprof) top10
1684.69MB of 1707.28MB total (98.68%)
Dropped 210 nodes (cum <= 8.54MB)
Showing top 10 nodes out of 31 (cum >= 1152.38MB)
      flat  flat%   sum%        cum   cum%
 1170.91MB 68.58% 68.58%  1170.91MB 68.58%  time.NewTimer
  258.62MB 15.15% 83.73%   259.03MB 15.17%  github.com/tideland/golib/cells.newCell
```

I did email you on the 24th but it might have ended up in your spam folder ;)

**Comment by TheMue** [comment]
Hmm, just an idea this morning:

- each cell gets a ticker, e.g. 1 second
- the cell backend loop consumes it while it is waiting for events; nothing is done here
- in `ProcessEvent()` the current time is taken in the beginning and in a select branch consuming this ticker channel
- here the time is taken again and if the difference is greater than the timeout the timeout error is returned

This should be resource friendly and I think one second (or even five seconds) is a good low value for a timeout. What do you think?

**Comment by TheMue** [comment]
So, solution looks good. And I'll also found an error in the `loop` package and fixed it. Will push the `cells` improvement together with the race fix.

**Comment by kung-foo** [comment]
Sounds good. I am not sure what the timeout should be (1 or 5), but this design (a per-cell ticker rather than a per-event timeout) provides only for the _responsiveness_ of the cell's behavior and not an absolute timeout. Meaning it says: "You have X seconds to receive an event plus a little bit of slop time. If you want a strict timeout, do it yourself".

If you go the ticker route, I would then lean towards a longer period (say 5 seconds) since this design will trigger a goroutine wake up.

Make sure the ticker is stopped in either `cell.stop()` or maybe via `cell.loop.Stop()` otherwise the ticker will leak.

**Comment by TheMue** [comment]
So having a ticker of 5s leading a configured 17s timeout to be a 20s timeout in reality would be fine for you? To me it would be fine.

**Comment by TheMue** [comment]
Changed to cell ticker based timeout.
